DROP_TABLE_SAGA = 'DROP TABLE IF EXISTS saga'
CREATE_TABLE_SAGA = """CREATE TABLE IF NOT EXISTS saga (
    id UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v1(),
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(100) NOT NULL,
    body TEXT NOT NULL)"""
INITIALIZE = [
    CREATE_TABLE_SAGA ]
REINITIALIZE = [
    DROP_TABLE_SAGA,
    CREATE_TABLE_SAGA ]
